name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Install Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: "5.2.0"
    - name: Build
      run: swift build --enable-test-discovery -Xswiftc -warnings-as-errors
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run SwiftLint --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
